version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - wait-for-it

  wait-for-it:
    image: willwill/wait-for-it
    entrypoint: ["sh", "-c", "exec sleep 10 && exec true"]
