apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app
spec:
  replicas: 2  # Deploy 2 instances of the app
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: simple-node-container
        image: myprojectreg.azurecr.io/simple-node-app:latest  # The Docker image from ACR
        ports:
        - containerPort: 3000  # App listens on port 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-service
spec:
  type: LoadBalancer  # Expose app to the internet
  selector:
    app: simple-node-app
  ports:
  - protocol: TCP
    port: 80  # External port (public-facing)
    targetPort: 3000  # Internal port (inside the container)

